### ISSUE TITLE
Support async createPngDataUri

### ISSUE THREAD

**Issue by monolithed** [johannschopplich/unlazy#17]
Hi! I believe it would be nice to add an asynchronous method that reads data using FileReader and does it faster.
Here is an [example](https://gist.github.com/fonsp/a4a2d127f35e72deec14227c1bdf3d04)

**Comment by johannschopplich** [comment]
Without having run benchmarks, Evan Wallace's [`rgbaToDataURL`](https://github.com/evanw/thumbhash/blob/main/js/thumbhash.js#L234) method should be suitable for most use-cases. It is the fastest implementation to encode an image to a PNG data URI across the board, and thus preferred. An async `createPngDataUri` would consequently make `lazyLoad` async, which I don't want to introduce.

Also, unlazy has a focus on SSR. Using `FileReader` is not viable in that case.
