### ISSUE TITLE
Don't include hashing algorithms, if not necessary

### ISSUE THREAD

**Issue by felixranesberger** [johannschopplich/unlazy#21]
### Describe the bug

When importing unlazy using `import { lazyLoad } from 'unlazy'`, the Thumbhash and Blurhash algorithms for decoding the hash to a valid data uri are always included.

This may not always be necessary, since we can also create a valid data uri on the serverside.

**Comment by johannschopplich** [comment]
I'm not sure if the `__ENABLE_HASH_DECODING__` variable is exposed for the default build. If so, you can use a plugin like Rollup replace to conditionally set it to `false`, which would tree-shake the hashing logic.

Source:
https://github.com/johannschopplich/unlazy/blob/96e854a984fe6c71cc6f4c9610e5f3cf60f85e5d/packages/core/src/lazyLoad.ts#L7-L8

If the variable is not exposed in the dist files, then we could enforce it to support tree-shaking.

**Comment by johannschopplich** [comment]
@felixranesberger My approach above won't work, since the `__ENABLE_HASH_DECODING__` variable will be dumped when bundling the library. Can you tell me which bundler you are using? There's still a workaround to exclude the hashing libraries.

**Comment by felixranesberger** [comment]
I'm using Vite to bundle the JS. 
So Rollup under the hood.

**Comment by johannschopplich** [comment]
@felixranesberger I have added a guide which should meet your requirements: [Build Flags](https://unlazy.byjohann.dev/cookbook/build-flags.html#disable-hash-decoding)
