### ISSUE TITLE
`<picture>` tag support

### ISSUE THREAD

**Issue by lenovouser** [johannschopplich/unlazy#22]
### Describe the feature

Most of my current projects use `<picture>` tags with different sizes and image codecs (WebP / JPG / PNG etc.) and I would love to be able to use unlazy for them, but it seems like currently only the `<img>` tag is supported.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/unlazy/issues).

**Comment by johannschopplich** [comment]
Hi there!

Happy to hear when people intend to use unlazy. Have you taken a look into the [Usage Guide](https://unlazy.byjohann.dev/guide/usage.html#usage)?

There is a section on `<picture>` tag support:

![grafik](https://github.com/johannschopplich/unlazy/assets/27850750/e7a3cb66-206e-41c0-9416-b7a299085c2a)

**Comment by lenovouser** [comment]
Yeah, my bad, didn't see the 2nd tab. Still figuring out why it doesn't work currently, will open another issue if it's the library, but most likely I am just doing something wrong.

**Comment by johannschopplich** [comment]
Yeah, the tab seems hidden a bit. 🙈 

I hope you get your issues resolved!

**Comment by lenovouser** [comment]
I found it, it apparently does not run when there is no native `src` attribute on the `<img>` inside the `<picture>`. I just had `data-src` and `data-srcset` on there.

**Comment by lenovouser** [comment]
Just set it to a blank base64 encoded 1×1 PNG and then it started working. I guess I need to put a thumbhash/blurhash in there?
