### ISSUE TITLE
[vue] No `sizes` attribute set when using `preload="true"`

### ISSUE THREAD

**Issue by felixranesberger** [johannschopplich/unlazy#27]
### Reproduction

```vue
<UnLazyImage
  :src-set="sourceSet"
  :placeholder-src="placeholderSrc"
  :auto-sizes="true"
  :width="image.width"
  :height="image.height"
  :alt="image.alt"
  :title="image.title"
  :preload="true"
  class="u-object-cover"
/>
```

### Describe the bug

When using `:auto-sizes="true"` in conjunction with `:preload="true"` the sizes attribute is not set.

This happens because `UnLazyImage.vue` checks if `props.preload === true` and uses the `loadImage` method to load the image directly. But the `loadImage` function is not checking, if the `sizes` attribute should be calculated.

**Comment by johannschopplich** [comment]
Great catch! Thanks for the thorough bug report. Should be fixed in https://github.com/johannschopplich/unlazy/commit/6903fe814cf10ab3491f60ead09337bd6a6fb08a.

**Comment by felixranesberger** [comment]
Thanks for the quick fix! 🎉
