### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tobimori** [johannschopplich/unlazy#29]
### Reproduction

I don't know what's causing this issue, but I can help you investigate. just message me.

### Describe the bug

This is the error in v0.10.0.
![CleanShot 2023-09-12 at 17 42 26@2x](https://github.com/johannschopplich/unlazy/assets/29142128/a31cb396-318e-406b-962d-075ec718205d)
![CleanShot 2023-09-12 at 17 41 38@2x](https://github.com/johannschopplich/unlazy/assets/29142128/aee4c97d-975b-423d-9438-808f5a3cc09a)

I get a similiar error in v0.9.0, just for a different type of code.
![CleanShot 2023-09-12 at 17 46 40@2x](https://github.com/johannschopplich/unlazy/assets/29142128/cd19e291-5754-4aa0-a712-e35e3cf9bd38)

**Comment by johannschopplich** [comment]
Thanks for the report! I think I have found the issue…

Could you please try [v0.10.1](https://github.com/johannschopplich/unlazy/releases/tag/v0.10.1) and give me a hint if it fixes your issue?

**Comment by tobimori** [comment]
thanks for the quick fix, this fixes the issue!
