### ISSUE TITLE
Transition

### ISSUE THREAD

**Issue by plcdnl** [johannschopplich/unlazy#32]
### Describe the feature

Will it be possible to add transitions in a future update?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/unlazy/issues).

**Comment by johannschopplich** [comment]
I guess so. How are you using unlazy – in vanilla JS or do you use one of the framework integrations?

An emitted event would probably be best to let the user initiate a transition. What you think?

**Comment by plcdnl** [comment]
I'm using the nuxt component. 
It would be nice to have a prop that defines it. So as to no longer have elements that replace each other
