### ISSUE TITLE
svelte 4 support

### ISSUE THREAD

**Issue by jonasfroeller** [johannschopplich/unlazy#39]
### Describe the feature

```bash
npm ERR! Found: svelte@4.2.8
npm ERR! peer svelte@"^3.54.0" from @unlazy/svelte@0.10.2
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/unlazy/issues).

**Comment by johannschopplich** [comment]
Added support for Svelte 4 in https://github.com/johannschopplich/unlazy/commit/e0d4cdaf0bbc84dd90f31972bf87a1a0db1a1180.

Please install [v0.10.3](https://github.com/johannschopplich/unlazy/releases/tag/v0.10.3) for this feature. Thx!
