### ISSUE TITLE
Error event

### ISSUE THREAD

**Issue by aloky** [johannschopplich/unlazy#42]
### Describe the feature

How can you tell if there was an error while downloading?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/unlazy/issues).

**Comment by johannschopplich** [comment]
What error do you expect to track down? Do you use a specific framework? Please elaborate. Thanks!

As of right now, unlazy will throw a warning if the image couldn't be rendered.

**Comment by aloky** [comment]
Sorry, but i cant find info, if image cant be show event, i use nuxt component.

**Comment by aloky** [comment]
example:

```
@error="(event: Error) => …"
```
