### ISSUE TITLE
Loaded event is not fired when used with preload attribute

### ISSUE THREAD

**Issue by chrispreisler** [johannschopplich/unlazy#49]
### Reproduction

https://stackblitz.com/edit/nuxt-3-xqdc5j?file=app.vue

### Describe the bug

Hey,

I think I found a bug for the loaded event. When using the preload prop the loaded event is not fired.

You can see this in the reproduction link. When you remove the preload attribute, it is working as expected and will remove the opacity-0 css class and also set the isLoaded ref to true.

If you have more questions, don't hesitate to ask me. :)

Thanks for your help.

Best regards
Chris

**Comment by johannschopplich** [comment]
Good catch! Thanks for reporting.

Fixed in https://github.com/johannschopplich/unlazy/commit/fc3013145fe93ea9834fd85d42f37296bf74c41d.

**Comment by chrispreisler** [comment]
Super cool, thanks for the fast fix. :)
