### ISSUE TITLE
Transition for Blurhash to Image

### ISSUE THREAD

**Issue by aloky** [johannschopplich/unlazy#51]
### Describe the feature

Add transition like

```
:transition="200"
```

200ms transition

example https://docs.expo.dev/versions/latest/sdk/image/#transition

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/unlazy/issues).

**Comment by M-GRV** [comment]
Was this completed? Or does this still need implementation? I could use this as it looks way better imho

**Comment by johannschopplich** [comment]
It isn't, I think. PR welcome!

**Comment by BlackDahlia313** [comment]
@aloky @johannschopplich 
https://github.com/user-attachments/assets/394e8847-81b1-4e13-b7d5-d1598ee8753a

Getting a PR together.

Its used like this:

`:transition="200"`

**Comment by BlackDahlia313** [comment]
Just switched out the implemenation so it could work across all packages. Now using the canvas api. Works across everything and is very solid in testing.


https://github.com/user-attachments/assets/09a4017f-44fd-4f29-9e1b-2ea87d44401d

**Comment by BlackDahlia313** [comment]
@aloky @johannschopplich 

https://github.com/johannschopplich/unlazy/pull/56

Let's party! :p

**Comment by plcdnl** [comment]
Hi, sorry the disturb, i was waiting for this. Any news?

**Comment by johannschopplich** [comment]
It has not been forgotten. I will review and release in the upcoming weeks. Thanks for your patience!

**Comment by EliasGit117** [comment]
any updates?
