### ISSUE TITLE
feat: Fixed size, varying density

### ISSUE THREAD

**Issue by trydofor** [johannschopplich/unlazy#54]
### Describe the feature

as [fixed-size-varying-density](https://jakearchibald.com/2015/anatomy-of-responsive-images/#[fixed-size-varying-density]) said, this feature provides,

* base on the biggest DPI image, e.g. 3x/image.png
* auto generate lower DPI image, e.g. 2x/image.png, 1x/image.png
* auto caculate the fixed width/height of image in 1x/image.png. e.g. width1x
* finally something like `<img src="~assets/1x/image.png" srcset="~assets/2x/image.png 2x, ~assets/3x/image.png 3x" :width="width1x"`

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/unlazy/issues).

**Comment by johannschopplich** [comment]
Hi there!
Is this a feature request? Is this a bug report? Please elaborate. 
PR welcome!

**Comment by trydofor** [comment]
> Hi there! Is this a feature request? Is this a bug report? Please elaborate. PR welcome!

feature request. I'm currently investigating this feature, I don't have a complete idea or solution yet, the current implementations of responsive images that I've searched for, are Varying size and density, so I'm not sure that on mobile, on HiDPI screens, I'm on the right track, and the community is so active, why am I the one who has a need for this?

**Comment by johannschopplich** [comment]
As this is a native image feature, it is supported:

```html
<img data-src="~assets/1x/image.png" data-srcset="~assets/2x/image.png 2x, ~assets/3x/image.png 3x" :width="width1x"
```
