### ISSUE TITLE
Feature request (Nuxt): manually load images

### ISSUE THREAD

**Issue by jjjuulliiaann** [johannschopplich/unlazy#8]
### Describe the feature

There is a method in the [docs](https://unlazy.byjohann.dev/guide/usage.html#manually-loading-images) to manually load an image before it enters the viewport. This is not yet possible when using the Nuxt integration, or am I missing something?

A practical use case could be a horizontal slideshow, where you could preload the previous and the next slide image manually, so that they are already loaded when the user switches slides. 

I tested it with a new prop named `immediateLoad` (see https://github.com/jjjuulliiaann/unlazy/commit/578424662e9a388ae5218d84dd7be17175706d8d) that triggers the loading when set to true. Do you think that could be a useful addition? I noticed you already had a similar implementation a while ago but removed it in https://github.com/johannschopplich/unlazy/commit/4e03c625a4f2deac36e0464f8e6f0e59c6cfb2c5.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/unlazy/issues).

**Comment by johannschopplich** [comment]
Thanks for the feature request! Great idea. Will take a look into it, but not this week. 🙂
